# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d7a5875ef37c5db32beace15b510d44b18f4fa1a5e2ff8b1f264eb1444eb2c9d47b96b092a9874b5c1a7c72c7d10658b61e9bd148bedb83914fba70d58527222

test:
  secret_key_base: 0f0d2b4cc939554c7bafc4b6b3cd0cebb3ff196845020fbac02d0c91c84ccd5b1b757644787fd5e063b7a365200eb7d27875da5fb67df3f7ab01700a0c9e37b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
